version: '3.8'

services:
  js-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - appnet
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  js-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    ports:
      - "4173:4173"
    env_file:
      - ./frontend/.env
    networks:
      - appnet
    environment:
      - NODE_ENV=production
      - VITE_BACKEND_URL=http://js-backend:3000
    depends_on:
      js-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  js-ai-service:
    build:
      context: ai-mcp-service
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    networks:
      - appnet
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://js-backend:3000
    depends_on:
      js-backend:
        condition: service_healthy

networks:
  appnet:
    driver: bridge