services:
  js-backend:
    build:
      context: ./backend
      dockerfile: ../backend/Dockerfile
    restart: unless-stopped
    init: true
    # Expose the port defined in Dockerfile (3000)
    ports:
      - "3000:3000"
    # Use env_file if .env exists in backend directory
    env_file:
      - ./backend/.env
    networks:
      - appnet
    # Add depends_on if backend requires external services (none detected)

  js-frontend:
    build:
      context: ./frontend
      dockerfile: ../frontend/Dockerfile
    restart: unless-stopped
    init: true
    # Expose the port defined in Dockerfile (4173)
    ports:
      - "4173:4173"
    # Use env_file if .env exists in frontend directory
    env_file:
      - ./frontend/.env
    networks:
      - appnet
    depends_on:
      - js-backend  # Ensure frontend starts after backend

  js-ai-service:
    build:
      context: ./ai-service
      dockerfile: ../ai-service/Dockerfile
    restart: unless-stopped
    init: true
    # No EXPOSE in Dockerfile, so no ports mapped
    # Use env_file if .env exists in ai-service directory
    # env_file: ./ai-service/.env  # Uncomment if .env file exists
    networks:
      - appnet
    depends_on:
      - js-backend  # If AI service needs backend API

networks:
  appnet:
    driver: bridge
    # Shared network for inter-service communication
